# Generated by Django 5.0.4 on 2024-04-15 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('nick_name', models.CharField(blank=True, max_length=256)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GenreMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2030)])),
                ('runtime', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('develope', 'In development'), ('pre', 'Pre production'), ('filming', 'Filming'), ('post', 'Post production'), ('released', 'Released')], default='released', max_length=8)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('plot', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='movies', to='myapi.artist')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies_directed', to='myapi.artist')),
                ('genre', models.ManyToManyField(blank=True, related_name='movies', to='myapi.genremovie')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)])),
                ('duration', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='music/')),
                ('lyrics', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='music_posters/')),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(blank=True, related_name='musics', to='myapi.genremusic')),
                ('main_singer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_musics', to='myapi.artist')),
                ('other_singers', models.ManyToManyField(blank=True, related_name='musics', to='myapi.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('number_of_seasons', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_episodes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('begin_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1920)])),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1920)])),
                ('average_runtime', models.PositiveIntegerField()),
                ('country', models.CharField(blank=True, max_length=64)),
                ('plot', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='serial_posters/')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('start_release_date', models.DateTimeField(blank=True, null=True)),
                ('end_release_date', models.DateTimeField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='series', to='myapi.artist')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_directed', to='myapi.artist')),
                ('genre', models.ManyToManyField(blank=True, related_name='series', to='myapi.genremovie')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapi.movie')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapi.serial')),
            ],
        ),
    ]
