# Generated by Django 5.0.4 on 2024-04-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Super User'), (2, 'Create, Update an Retrieve'), (3, 'just Retrieve')], default=3),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
