# Generated by Django 5.0.4 on 2024-04-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_staff_access_level_alter_staff_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='access_level',
        ),
    ]
