# Generated by Django 5.0.4 on 2024-04-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_genremovie_title_alter_genremusic_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='genremovie',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='genremusic',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
