# Generated by Django 5.0.4 on 2024-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_artist_unique_together_alter_genremovie_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
