# Generated by Django 5.0.4 on 2024-06-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_movie_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
